apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testapp2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testapp2
    app.kubernetes.io/part-of: testapp2
  name: testapp2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: testapp2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: testapp2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/klakshma-tenant/testapp2/testapp2@sha256:d64052fafa94941d84ff0b6ab5a970ac057b3e6419a73363ac13e883dff728d1
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
