apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testapp2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testapp2
    app.kubernetes.io/part-of: testapp2
  name: testapp2zjnu
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: testapp2
    weight: null
status: {}
